// GET /api/deepdive?id=&title=&artist=[&fast=1]
// Phase 2 (AI-first, two-phase) — the knowledge pipeline:
//   1) cache (in-memory)            -> instant on repeats
//   2) gather facts from open data  -> MusicBrainz + Wikipedia (free, no key)
//   3) AI writes the cards          -> Anthropic Claude, grounded in those facts but
//                                      also allowed to use well-known music knowledge
//                                      (with anti-hallucination guardrails)
//   4) graceful fallback            -> plain open-data cards if no key / any failure
//
// Two-phase: ?fast=1 returns open-data cards instantly and (if a key is set) flags
// _meta.aiPending so the client fetches the AI-written version in a second call.
// Facts are cached between the two calls, so open data is only gathered once.
//
// To enable the AI step, add an Application Setting in Azure (Configuration):
//   ANTHROPIC_API_KEY = sk-ant-...

const A = require("../shared/auth");
const MB_BASE = "https://musicbrainz.org/ws/2";
const MB_UA = "geeek/1.0 (https://geeek.fm)"; // MusicBrainz requires a UA
const WIKI = "https://en.wikipedia.org/api/rest_v1/page/summary/";
const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_MODEL = "claude-haiku-4-5-20251001"; // change here if your account uses a different id

// Shared cross-user cache (Upstash Redis, optional). Inert until both env vars are set:
//   UPSTASH_REDIS_REST_URL, UPSTASH_REDIS_REST_TOKEN  (add in Azure → Configuration)
// When set, a song generated by ANY user is served instantly to everyone — no repeat Claude call.
const VERSION = "2.1"; // bump to invalidate the shared cache when the AI prompt changes
const REDIS_URL = process.env.UPSTASH_REDIS_REST_URL;
const REDIS_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN;
const SHARED_TTL = 60 * 60 * 24 * 90; // keep cached cards for 90 days

const cache = new Map();       // key -> finished payload (AI or open-data)
const factsCache = new Map();  // key -> gathered facts (shared by fast + full calls)
const CACHE_MAX = 500;
function capped(map) { if (map.size > CACHE_MAX) map.clear(); }
function norm(s) { return (s || "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
// Canonical key: the STORY is about the song, so ignore edition/feature noise that would otherwise
// split one song into several cache entries (and several different AI stories).
function primaryArtist(a) { return String(a || "").split(/,|&|;|\/|\bfeat\.?\b|\bfeaturing\b|\bwith\b|\bx\b|\bvs\.?\b/i)[0]; }
function songTitleBase(t) { return String(t || "").replace(/\([^)]*\)/g, " ").replace(/\[[^\]]*\]/g, " ").replace(/\s[-–—]\s.*$/, " "); }
function cacheKey(q) { return ("song:" + norm(songTitleBase(q.title)) + "|" + norm(primaryArtist(q.artist))).replace(/\s+/g, "_"); }

async function jget(url, headers, ms) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), ms || 8000);
  try {
    const r = await fetch(url, { headers: headers || {}, signal: ctrl.signal });
    if (!r.ok) return null;
    return await r.json();
  } catch (e) { return null; } finally { clearTimeout(timer); }
}

// ---- shared cache (Upstash Redis REST). No-op when env vars aren't set. ----
async function redisCmd(cmd, ms) {
  if (!REDIS_URL || !REDIS_TOKEN) return null;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), ms || 4000);
  try {
    const r = await fetch(REDIS_URL, {
      method: "POST",
      headers: { "Authorization": "Bearer " + REDIS_TOKEN, "Content-Type": "application/json" },
      body: JSON.stringify(cmd),
      signal: ctrl.signal
    });
    if (!r.ok) return null;
    const j = await r.json();
    return (j && Object.prototype.hasOwnProperty.call(j, "result")) ? j.result : null;
  } catch (e) { return null; } finally { clearTimeout(timer); }
}
async function sharedGet(skey) {
  const v = await redisCmd(["GET", skey]);
  if (!v || typeof v !== "string") return null;
  try { return JSON.parse(v); } catch (e) { return null; }
}
async function sharedSet(skey, payload) {
  try { await redisCmd(["SET", skey, JSON.stringify(payload), "EX", String(SHARED_TTL)]); } catch (e) {}
}
// First-writer-wins: only set if the song has no story yet. Returns true if WE wrote it.
async function sharedSetNX(skey, payload) {
  try { return (await redisCmd(["SET", skey, JSON.stringify(payload), "NX", "EX", String(SHARED_TTL)])) === "OK"; }
  catch (e) { return false; }
}

async function bestRecording(title, artist) {
  const query = encodeURIComponent(`recording:"${title}"` + (artist ? ` AND artist:"${artist}"` : ""));
  const search = await jget(`${MB_BASE}/recording?query=${query}&fmt=json&limit=8`, { "User-Agent": MB_UA });
  const recs = (search && search.recordings) || [];
  if (!recs.length) return null;
  const nt = norm(title), na = norm(artist);
  let best = null, bestScore = -1;
  for (const r of recs) {
    const credit = (r["artist-credit"] || []).map(a => a.name).join(", ");
    let score = (r.score || 0);
    if (norm(r.title) === nt) score += 30;
    if (na && norm(credit).includes(na)) score += 40;
    if ((r["first-release-date"] || "").slice(0, 4)) score += 5;
    if (score > bestScore) { bestScore = score; best = r; }
  }
  return best;
}

function addCredit(map, type, name) {
  if (!type || !name) return;
  const t = String(type).toLowerCase();
  if (!map.has(t)) map.set(t, new Set());
  map.get(t).add(name);
}
function flattenCredits(map) {
  const order = ["composer", "lyricist", "writer", "producer", "vocal", "performer", "instrument", "arranger", "engineer", "mix"];
  const keys = Array.from(map.keys()).sort((a, b) => {
    const ia = order.indexOf(a), ib = order.indexOf(b);
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
  });
  const out = [];
  for (const k of keys) {
    const names = Array.from(map.get(k)).slice(0, 4);
    if (names.length) out.push(`${k}: ${names.join(", ")}`);
  }
  return out;
}

async function wikiSummary(candidates) {
  for (const c of candidates) {
    const s = await jget(WIKI + encodeURIComponent(c), {});
    if (s && s.extract && s.type !== "disambiguation") return s.extract.trim();
  }
  return "";
}
// Music-validated artist summary: skip non-music entities (e.g. "Cream" the dairy product) so the story
// never describes the wrong thing.
const DEEP_MUSIC_RE = /\b(band|duo|trio|quartet|quintet|sextet|musician|singer|songwriter|rapper|record producer|producer|dj|group|rock|pop|hip[\s-]?hop|metal|jazz|orchestra|ensemble|composer|indie|folk|punk|soul|reggae|electronic|country|blues|rnb|r&b|guitarist|drummer|bassist|vocalist|discograph)\b/i;
async function wikiArtistSummary(candidates) {
  for (const c of candidates) {
    const s = await jget(WIKI + encodeURIComponent(c), {});
    if (!s || s.type === "disambiguation" || !s.extract) continue;
    if (!DEEP_MUSIC_RE.test((s.description || "") + " " + (s.extract || ""))) continue;
    return s.extract.trim();
  }
  return "";
}

async function gatherFacts(title, artist, context) {
  const facts = { title, artist, year: "", mbArtist: "", credits: [], wiki: "", wikiArtist: "" };
  const creditMap = new Map();

  const rec = await bestRecording(title, artist);
  if (rec) {
    facts.mbArtist = (rec["artist-credit"] || []).map(a => a.name).join(", ");
    facts.year = (rec["first-release-date"] || "").slice(0, 4);

    const det = await jget(`${MB_BASE}/recording/${rec.id}?inc=artist-rels+work-rels&fmt=json`, { "User-Agent": MB_UA });
    let workId = "";
    if (det && Array.isArray(det.relations)) {
      for (const rel of det.relations) {
        if (rel.artist && rel.type) addCredit(creditMap, rel.type, rel.artist.name);
        if (rel.work && rel.work.id && !workId) workId = rel.work.id;
      }
    }
    if (workId) {
      const work = await jget(`${MB_BASE}/work/${workId}?inc=artist-rels&fmt=json`, { "User-Agent": MB_UA });
      if (work && Array.isArray(work.relations)) {
        for (const rel of work.relations) {
          if (rel.artist && rel.type) addCredit(creditMap, rel.type, rel.artist.name);
        }
      }
    }
  }
  facts.credits = flattenCredits(creditMap);

  const songCands = artist
    ? [`${title} (${artist} song)`, `${title} (song)`, title]
    : [`${title} (song)`, title];
  facts.wiki = await wikiSummary(songCands);
  if (artist) {
    facts.wikiArtist = await wikiArtistSummary([artist, `${artist} (band)`, `${artist} (musician)`, `${artist} (singer)`]);
  }
  return facts;
}

function factsBlock(f) {
  let s = `Song title: ${f.title}\nArtist (as queried): ${f.artist || "unknown"}\n`;
  if (f.mbArtist) s += `Artist credit (MusicBrainz): ${f.mbArtist}\n`;
  if (f.year) s += `First release year: ${f.year}\n`;
  if (f.credits.length) s += `Credits / relationships: ${f.credits.slice(0, 12).join("; ")}\n`;
  if (f.wiki) s += `Wikipedia (song): ${f.wiki}\n`;
  if (f.wikiArtist) s += `Wikipedia (artist): ${f.wikiArtist}\n`;
  if (!f.mbArtist && !f.wiki && !f.wikiArtist) s += `(Open-data lookup was thin for this one.)\n`;
  return s;
}

async function writeCardsWithClaude(apiKey, f, context) {
  const system =
    "You are a warm, knowledgeable music writer creating short 'deep dive' cards for someone who is listening to this song right now. " +
    "Your goal: spark curiosity and joy about the music they love, and — where it feels natural — gently remind them that the best thing to do next is to go live life: feel it, share it, get outside. Never force that nudge.\n\n" +
    "GROUNDING RULES (important):\n" +
    "- The FACTS block (from MusicBrainz + Wikipedia) is your source of truth. Prefer it for all names, dates, credits, and specific claims.\n" +
    "- You MAY enrich the cards with widely-known, well-established context about the song, artist, genre, era, and influences from your own knowledge — this is encouraged so the cards feel rich and alive.\n" +
    "- NEVER fabricate specific credits, collaborators, chart positions, dates, lyrics, or quotes you are not confident are correct. When unsure about a specific, stay general or leave it out. Accuracy beats flourish.\n" +
    "- If the facts are thin AND you genuinely do not recognize the song, be honest and keep it general rather than inventing details.\n" +
    "- Do not reproduce song lyrics.\n\n" +
    "Output STRICT JSON only — no prose, no markdown fences.";
  const user =
    `Facts:\n${factsBlock(f)}\n\n` +
    `Write BOTH an editorial "story" (a short long-read) AND five compact "cards", as STRICT JSON in exactly this shape. Ground every name, date and credit in the facts; you may add well-known context; never fabricate specifics or reproduce lyrics. Keep it vivid and concise:\n` +
    `{"story":{` +
    `"headline":"a vivid narrative title for this song's story — max 8 words, do NOT simply repeat the song title",` +
    `"dek":"1 short sentence that hooks the reader into the story",` +
    `"body":[` +
    `{"type":"p","text":"opening — set the scene in 1-2 short sentences"},` +
    `{"type":"quote","text":"a short punchy pull-quote, max 12 words"},` +
    `{"type":"p","text":"how it was made and who made it, 1-2 short sentences"},` +
    `{"type":"p","text":"its connection, influence, sample or legacy, 1-2 short sentences"},` +
    `{"type":"quote","text":"a second short pull-quote, max 12 words"},` +
    `{"type":"p","text":"closing — a surprising fact or a warm nudge to go enjoy it, 1-2 short sentences"}` +
    `]},` +
    `"cards":[` +
    `{"kicker":"The story","title":"max 6 words","body":"1 short vivid sentence on what this song is and why it matters","extra":"1 short sentence going deeper on its origin or meaning"},` +
    `{"kicker":"The people","title":"max 6 words","body":"who made it — artist and key writer/producer (brief)","extra":"1 short sentence on how they shaped it"},` +
    `{"kicker":"Connections","title":"max 6 words","body":"how it connects to other music or scenes (brief)","extra":"1 short sentence on an influence, sample, or descendant"},` +
    `{"kicker":"Fun facts","title":"max 6 words","body":"1 quick, surprising fun fact","extra":"1 more bite-sized fact — keep it short"},` +
    `{"kicker":"Did you know","title":"max 6 words","body":"one surprising, shareable fact","extra":"1 short sentence — and, if it fits, a warm nudge to go enjoy it"}` +
    `]}`;
  const body = { model: ANTHROPIC_MODEL, max_tokens: 1400, system, messages: [{ role: "user", content: user }] };
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 20000);
  try {
    const r = await fetch(ANTHROPIC_URL, {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify(body), signal: ctrl.signal
    });
    if (!r.ok) { context.log("anthropic http", r.status); return null; }
    const data = await r.json();
    const text = (data.content && data.content[0] && data.content[0].text) || "";
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return null;
    const parsed = JSON.parse(match[0]);
    return (parsed && Array.isArray(parsed.cards)) ? { cards: parsed.cards, story: (parsed.story && parsed.story.headline) ? parsed.story : null } : null;
  } catch (e) { context.log("anthropic error", e.message); return null; } finally { clearTimeout(timer); }
}

// Truncate at a sentence end when possible, else at a word boundary (+ ellipsis) — never mid-word.
function clip(text, maxChars) {
  if (!text) return "";
  const t = String(text).replace(/\s+/g, " ").trim();
  if (t.length <= maxChars) return t;
  const cut = t.slice(0, maxChars);
  const end = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("! "), cut.lastIndexOf("? "));
  if (end > maxChars * 0.5) return cut.slice(0, end + 1).trim();
  const sp = cut.lastIndexOf(" ");
  return (sp > 0 ? cut.slice(0, sp) : cut).replace(/[,;:.\-\s]+$/, "").trim() + "…";
}
function templateCards(f) {
  const yr = f.year ? ` (${f.year})` : "";
  const who = f.mbArtist || f.artist || "the artist";
  const credits = f.credits.length ? f.credits.slice(0, 6).join(" · ") : "Producer/writer credits will fill in from open data.";
  const wiki = f.wiki || f.wikiArtist || "A short, sourced background will appear here.";
  return [
    { kicker: "The story", title: `About “${f.title}”${yr}`, body: clip(wiki, 150), extra: clip(wiki.slice(150), 160) || "More background as we enrich the data." },
    { kicker: "The people", title: "Who made it", body: `Performed by ${who}.`, extra: credits },
    { kicker: "Connections", title: "How it connects", body: `Related artists and influences around ${who}.`, extra: "Built from open relationship data (MusicBrainz)." },
    { kicker: "Fun facts", title: "Quick facts", body: f.wikiArtist ? clip(f.wikiArtist, 150) : "Fun facts appear here once AI writing is on.", extra: f.wikiArtist ? clip(f.wikiArtist.slice(150), 150) : "" },
    { kicker: "Did you know", title: "A fact to share", body: f.wikiArtist ? clip(f.wikiArtist, 110) : `Tap to learn more about ${who}.`, extra: "Then go enjoy it out loud." }
  ];
}

function templateStory(f, cards) {
  const who = f.mbArtist || f.artist || "the artist";
  const yr = f.year ? (" (" + f.year + ")") : "";
  const body = [];
  if (f.wiki) body.push({ type: "p", text: clip(f.wiki, 500) });
  body.push({ type: "p", text: "Performed by " + who + (f.year ? (", first released in " + f.year) : "") + "." });
  if (f.credits && f.credits.length) body.push({ type: "p", text: f.credits.slice(0, 6).join(" \u00b7 ") });
  if (f.wikiArtist) body.push({ type: "p", text: clip(f.wikiArtist, 360) });
  if (body.length < 2) body.push({ type: "p", text: "A fuller story will appear here as we enrich the data." });
  // Distinct hook — deliberately NOT a slice of the body, so it never repeats the opening paragraph.
  const dek = "The story behind “" + f.title + "”" + (who && who !== "the artist" ? " by " + who : "") + ".";
  return { headline: f.title + yr, dek: dek, body: body };
}

async function getFacts(key, q, context) {
  let facts = factsCache.get(key);
  if (!facts) {
    facts = await gatherFacts(q.title, q.artist, context);
    capped(factsCache);
    factsCache.set(key, facts);
  }
  return facts;
}

module.exports = async function (context, req) {
  if (A.blockIfUnauthed(context, req)) return;
  const q = {
    id: (req.query && req.query.id) || "",
    title: ((req.query && req.query.title) || "").trim(),
    artist: ((req.query && req.query.artist) || "").trim()
  };
  const fast = !!(req.query && (req.query.fast === "1" || req.query.fast === "true"));

  // Diagnostics: /api/deepdive?diag=1 — reports shared-cache wiring (no secret values exposed).
  if (req.query && req.query.diag === "1") {
    var probe = {};
    if (REDIS_URL && REDIS_TOKEN) {
      var pctrl = new AbortController();
      var ptimer = setTimeout(function () { pctrl.abort(); }, 6000);
      try {
        var pr = await fetch(REDIS_URL, {
          method: "POST",
          headers: { "Authorization": "Bearer " + REDIS_TOKEN, "Content-Type": "application/json" },
          body: JSON.stringify(["PING"]),
          signal: pctrl.signal
        });
        probe.httpStatus = pr.status;
        probe.body = (await pr.text()).slice(0, 160); // PONG / error message — never contains the token
      } catch (e) { probe.error = String((e && e.message) || e).slice(0, 160); }
      finally { clearTimeout(ptimer); }
    } else {
      probe.note = "url or token missing";
    }
    context.res = {
      status: 200,
      headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
      body: {
        version: VERSION,
        redisUrlSet: !!REDIS_URL,
        redisTokenSet: !!REDIS_TOKEN,
        redisTokenLen: REDIS_TOKEN ? REDIS_TOKEN.length : 0,
        redisUrlHost: REDIS_URL ? (REDIS_URL.split("/")[2] || "?") : null,
        probe: probe
      }
    };
    return;
  }

  // Admin cleanup (token-guarded; server-side only, never exposed to clients):
  // /api/deepdive?diag=del&key=<exact-shared-key>&t=<token> — deletes ONE orphaned/duplicate cache key.
  if (req.query && req.query.diag === "del") {
    if (req.query.t !== "gk9f3k2m8x7q_admin") { context.res = { status: 403, headers: { "Content-Type": "application/json" }, body: { error: "forbidden" } }; return; }
    const k = String(req.query.key || "");
    const deleted = k ? await redisCmd(["DEL", k]) : 0;
    context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: { key: k, deleted: deleted } };
    return;
  }

  // Read-only cache inspector: /api/deepdive?diag=keys&pat=protection — lists matching shared-cache
  // entries with their story headline (public content only; no secrets). Helps spot duplicates.
  if (req.query && req.query.diag === "keys") {
    const raw = String(req.query.pat || "").toLowerCase().replace(/[^a-z0-9]+/g, "*");
    const pat = "sdd:*" + (raw || "") + "*";
    let cursor = "0"; const keys = [];
    for (let i = 0; i < 30; i++) {
      const res = await redisCmd(["SCAN", cursor, "MATCH", pat, "COUNT", "300"]);
      if (!res || !Array.isArray(res)) break;
      cursor = res[0]; (res[1] || []).forEach(function (k) { keys.push(k); });
      if (cursor === "0") break;
    }
    const entries = [];
    for (const k of keys.slice(0, 50)) {
      const v = await sharedGet(k);
      entries.push({ key: k, headline: v && v.story && v.story.headline, generatedAt: v && v._meta && v._meta.generatedAt });
    }
    context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: { pattern: pat, count: keys.length, entries: entries } };
    return;
  }

  if (!q.title) {
    context.res = { status: 400, headers: { "Content-Type": "application/json" }, body: { error: "Provide ?title=" } };
    return;
  }

  const key = cacheKey(q);
  const skey = "sdd:" + VERSION + ":" + key; // shared-cache key (versioned)

  // A finished (AI or final) payload always wins — instant.
  if (cache.has(key)) {
    context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "public, max-age=86400" }, body: cache.get(key) };
    return;
  }

  // Shared cross-user cache: if anyone has already generated this song, serve it instantly.
  const shared = await sharedGet(skey);
  if (shared && shared.cards && shared.cards.length) {
    cache.set(key, shared);
    context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "public, max-age=86400" }, body: shared };
    return;
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  const facts = await getFacts(key, q, context);

  // Phase 1 — instant open-data cards. If a key is set, tell the client an AI upgrade is coming.
  if (fast) {
    const fastCards = templateCards(facts);
    const payload = {
      track: { id: q.id, title: q.title, artist: q.artist },
      cards: fastCards,
      story: templateStory(facts, fastCards),
      _meta: {
        source: apiKey ? "open-data (AI pending)" : "open-data (add ANTHROPIC_API_KEY for AI)",
        aiPending: !!apiKey,
        year: facts.year || null,
        generatedAt: new Date().toISOString()
      }
    };
    // Not cached as final, so the follow-up full call still runs the AI.
    context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: payload };
    return;
  }

  // Phase 2 (or single-call) — AI cards if a key is set, else open-data.
  let ai = null;
  if (apiKey) ai = await writeCardsWithClaude(apiKey, facts, context);
  const aiUsed = !!(ai && ai.cards && ai.cards.length);
  const cards = aiUsed ? ai.cards : templateCards(facts);
  const story = (aiUsed && ai.story) ? ai.story : templateStory(facts, cards);

  let payload = {
    track: { id: q.id, title: q.title, artist: q.artist },
    cards, story,
    _meta: { source: aiUsed ? "ai+open-data" : "open-data (add ANTHROPIC_API_KEY for AI)", year: facts.year || null, generatedAt: new Date().toISOString() }
  };
  capped(cache);
  if (aiUsed) {
    // ONE canonical story per song: first request to finish LOCKS the story (SET NX). The AI is
    // non-deterministic, so if two requests race, the loser adopts the winner's story instead of
    // caching its own — every device/instance then converges to exactly one story.
    const won = await sharedSetNX(skey, payload);
    if (!won) {
      const existing = await sharedGet(skey);
      if (existing && existing.cards && existing.cards.length) payload = existing;
    }
    cache.set(key, payload);
  } else if (!apiKey) {
    // No AI key -> template is the permanent fallback; cache it. (If a key exists but AI failed
    // transiently, don't cache the template so the next request retries the AI.)
    cache.set(key, payload);
  }

  context.res = { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "public, max-age=86400" }, body: payload };
};
